title: art.dblock.org | art blog
locale: en_US
url:
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-paginate
kramdown:
  input: GFM
owner:
  name: "Daniel Doubrovkine"
  avatar: blog.gif
  bio: "Drawing sanguines, conté crayon, photography, private collection, theatre and art log. CTO at <a href='https://www.artsy.net'>artsy.net</a>, <a href='https://www.instagram.com/artdblockdotorg'>@artdblockdotorg</a>, <a href='https://www.instagram.com/kidsandsharks'>@kidsandsharks</a>."
  email: dblock@dblock.org
  disqus-shortname: dblockdotorg-art
  twitter: dblockdotorg
  facebook:
  google:
    plus:
    analytics: UA-4756101-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github:
  stackoverflow:
  linkedin:
  instagram: artdblockdotorg
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
paginate: 35
suggest_url: https://github.com/dblock/art.dblock.org/issues/new
google_custom_search: "015938957525977311805:cuw72ypmpmq"
